/**
 * SensorIngestionService - Handles sensor data ingestion with validation.
 * 
 * Requirements: 1.1, 1.2, 1.3
 * 
 * Responsibilities:
 * - Validate incoming sensor data
 * - Generate unique message IDs and timestamps
 * - Build topics from sensor data
 * - Create IngestedMessage objects for downstream processing
 */

import { randomUUID } from 'crypto';
import {
  SensorData,
  validateSensorData,
  ValidationResult,
} from '../types/sensor-data.js';
import {
  IngestedMessage,
  createIngestedMessage,
} from '../types/ingested-message.js';

/**
 * Result of an ingestion operation.
 */
export interface IngestionResult {
  success: boolean;
  messageId?: string;
  message?: IngestedMessage;
  error?: string;
}

/**
 * SensorIngestionService handles the ingestion of sensor data.
 */
export class SensorIngestionService {
  private generatedMessageIds: Set<string> = new Set();

  /**
   * Generates a unique message ID.
   * Uses UUID v4 for uniqueness guarantee.
   * 
   * @returns A unique message ID string
   */
  generateMessageId(): string {
    const messageId = randomUUID();
    this.generatedMessageIds.add(messageId);
    return messageId;
  }

  /**
   * Checks if a message ID was generated by this service instance.
   * Useful for testing uniqueness properties.
   * 
   * @param messageId - The message ID to check
   * @returns true if the message ID was generated by this instance
   */
  hasGeneratedMessageId(messageId: string): boolean {
    return this.generatedMessageIds.has(messageId);
  }

  /**
   * Gets all message IDs generated by this service instance.
   * 
   * @returns Set of all generated message IDs
   */
  getGeneratedMessageIds(): Set<string> {
    return new Set(this.generatedMessageIds);
  }

  /**
   * Clears the tracking of generated message IDs.
   * Useful for testing.
   */
  clearGeneratedMessageIds(): void {
    this.generatedMessageIds.clear();
  }

  /**
   * Validates sensor data against the schema.
   * 
   * @param data - Unknown input to validate
   * @returns ValidationResult with parsed data or error message
   */
  validateSensorData(data: unknown): ValidationResult {
    return validateSensorData(data);
  }

  /**
   * Ingests sensor data, validates it, and creates an IngestedMessage.
   * 
   * Requirements:
   * - 1.1: Validate data structure and accept valid payloads
   * - 1.2: Reject invalid data with error response
   * - 1.3: Assign unique message ID and timestamp
   * 
   * @param data - Unknown input to ingest
   * @returns IngestionResult with success status and message or error
   */
  ingest(data: unknown): IngestionResult {
    // Validate the incoming data
    const validationResult = this.validateSensorData(data);

    if (!validationResult.success) {
      return {
        success: false,
        error: validationResult.error,
      };
    }

    // Generate unique message ID
    const messageId = this.generateMessageId();

    // Create the ingested message with topic
    const ingestedMessage = createIngestedMessage(
      validationResult.data as SensorData,
      messageId
    );

    return {
      success: true,
      messageId,
      message: ingestedMessage,
    };
  }

  /**
   * Ingests multiple sensor data payloads.
   * Each payload is processed independently.
   * 
   * @param dataArray - Array of unknown inputs to ingest
   * @returns Array of IngestionResults
   */
  ingestBatch(dataArray: unknown[]): IngestionResult[] {
    return dataArray.map((data) => this.ingest(data));
  }
}
